### PR TITLE
Limit output of validator

### PR DESCRIPTION
**Pull request by c-martinez**
Perhaps it is more useful to print only a [human readable message explaining the error.](https://python-jsonschema.readthedocs.org/en/latest/errors/) instead of the error itself, which outputs the complete schema each time and makes it a bit harder to read ?

### CODE REVIEW

**Comment by sverhoeven** [comment]
The human readable message does not tell me which property has a bad value, if that is added I am OK with the smaller error message.

**Comment by c-martinez** [comment]
Would including the [schema path](https://python-jsonschema.readthedocs.org/en/latest/errors/#jsonschema.exceptions.ValidationError.relative_schema_path) make you happy?

**Comment by sverhoeven** [comment]
Yep, that would work

**Comment by c-martinez** [comment]
Good :-)

**Comment by blootsvoets** [comment]
Merged `gh-pages` so the branch can be easily pulled. Also formatted the message a bit more.

**Pull request merged**
