### PR TITLE
Add Common Sense

### PR DESCRIPTION
**Pull request by c-martinez**
Adding common Sense

`estep validate` didn't flag any issues, but I'm not sure it is 100% right.

### CODE REVIEW

**Comment by sverhoeven** [comment]
Please list languages on separate lines and wait for #19 to be merged and update the Markdown accordingly.

**Comment by sverhoeven** [comment]
PR #19 has been merged, 
Could you merge the gh-pages branch into the cmartinez branch and make your docs valid.

**Comment by c-martinez** [comment]
Now it is spitting a couple of errors :+1: -- will fix and send new PR

**Comment by wrvhage** [comment]
It’s mostly carping about missing descriptions of people etc.
Be careful to uphold Joris’ new, flatter, schema as opposed to the old nested one.

Willem

| New Call for Proposals 2016 | More information www.esciencecenter.nl/project-calls<applewebdata://F080E7EB-ADB6-4560-BE2B-42A2F19F4E41/www.eScienceCenter.nl/project-calls> |
| Funding opportunities for data-driven and compute-intensive research |

| Dr. Willem van Hage | Technology Lead Data Management and Analytics | email: w.vanhage@esciencecenter.nl<mailto:w.vanhage@esciencecenter.nl> |
| Netherlands eScience Center | Science Park 140 | 1098 XG Amsterdam | The Netherlands |
| The Netherlands eScience Center is a joint initiative by SURF and NWO | www.nlesc.nl<http://www.nlesc.nl/> |

On 05 Apr 2016, at 10:14, c-martinez <notifications@github.com<mailto:notifications@github.com>> wrote:


Now it is spitting a couple of errors [:+1:]  -- will fix and send new PR

**Pull request merged**
