### PR TITLE
My additions

### PR DESCRIPTION
**Pull request by egpbos**
My personal, projects and related organisations pages.

### CODE REVIEW

**Comment by blootsvoets** [comment]
Two questions:
- Could you use the new link notation in referenced people and persons? E.g. `"website": "http://www.esciencecenter.nl"` instead of `"link": { "url": "http://www.esciencecenter.nl", "description": "website"}`
- Could you change `organization` to `affiliation` and make it an array?

I see you already did this for the projects and persons themselves, but not for hierarchical objects such as `_project/hadrianus.md#/principalInvestigator`

If you pull from gh-pages, it should now check for these errors.

**Comment by egpbos** [comment]
I merged the latest upstream changes into my branch, but the files still validate just fine with the outdated link structure.

**Comment by egpbos** [comment]
The checks now fail because the links to software projects I use or am involved with do not exist as pages yet, since I'm not the one that should create them (xtas -> @larsmans, cptm -> @jvdzwaan) or if I create them I create a cascade of the same issue, since not all the persons involved exist yet (pattyvis -> whole pattyvis team).

The quickest way to make sure that this does not create a bunch of failed checks tomorrow when people start adding random stuff in random order is probably to turn off the internal link checking for the time being.

**Comment by egpbos** [comment]
Ok, the other way to fix it (which I did here) is to simply omit the links in the files and leave the fields to be filled in.

**Comment by blootsvoets** [comment]
OK great. Either way works: removing links or creating stub personal files.

**Pull request merged**
